version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ephemera
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/app
      - ~/.kube:/root/.kube:ro
      - ~/.aws:/root/.aws:ro
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ephemera
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ./api/.env
    depends_on:
      - postgres
      - redis

  celery_worker:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: celery -A app.core.celery_app worker --loglevel=info --queues=environment,cleanup
    volumes:
      - ./api:/app
      - ~/.kube:/root/.kube:ro
      - ~/.aws:/root/.aws:ro
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ephemera
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ./api/.env
    depends_on:
      - postgres
      - redis

  celery_beat:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: celery -A app.core.celery_app beat --loglevel=info
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ephemera
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ./api/.env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
